FROM continuumio/miniconda3
RUN apt-get update
ARG API_HOST
ARG API_PORT
ENV IOT_API_URL=http://$API_HOST:$API_PORT
COPY . ./
RUN pip3 install -e .
RUN pip3 install -r example/requirements.txt
